spring.datasource.url=jdbc:mysql://localhost:${MYSQL_PORT:3306}/${MYSQL_DATABASE:evaluaciondb}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${MYSQL_USER:evaluacion}
spring.datasource.password=${MYSQL_PASSWORD:evaluacion}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=false
